# Generated by Django 4.1.2 on 2022-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_service', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users_online',
            field=models.CharField(default=' ', max_length=1500),
            preserve_default=False,
        ),
    ]
