# Generated by Django 4.1.2 on 2022-12-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_service', '0003_room_users_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users_online',
        ),
    ]
